### ISSUE TITLE
Move social networks to footer

### ISSUE THREAD

**Issue by crashzk** [Rushaway/sourcebans-web-theme-fluent#10]
Could it be that changing social networks to footer, centralized, wouldn't it be more beautiful? Just aesthetics...

![image](https://user-images.githubusercontent.com/32937653/221389074-2d167d42-bdd9-4dc6-bba9-58ac4ad7923f.png)

**Comment by Rushaway** [comment]
It's not planned to move them for now. But feel free to edit your footer.tpl and move them.
