### ISSUE TITLE
[BUG] Protests and Submissions

### ISSUE THREAD

**Issue by tslashd** [Rushaway/sourcebans-web-theme-fluent#11]
I updated to latest SourceBans++ dev version and downloaded this fork of **aXenDev**'s theme as old one stopped working.
Since then I have found this issue which was not present with the previous version of the theme.
Ban protests and submissions are not displayed in the panel, pictures below:
Totals:
![image](https://user-images.githubusercontent.com/74899888/229272637-7bf5b9e5-a419-41bf-b461-842744b55e6b.png)
Protests (same is shown in Archive tab):
![image](https://user-images.githubusercontent.com/74899888/229272656-e2b6ddbe-427d-4e9a-a2b1-ebe19a0a179f.png)
 Submissions:
![image](https://user-images.githubusercontent.com/74899888/229272669-bf4e1e81-0e0f-49c9-b0b9-acf0d0e8dd57.png)

Also noticed some icons not showing up properly:
![image](https://user-images.githubusercontent.com/74899888/229272854-c1593c3e-ae21-4181-8029-6045fac0e2e6.png)

P.S: It may not be a bug from theme side I suppose (only assuming that cause they worked correctly with old theme) but would greatly appreciate any tips on fixing these.

**Comment by Rushaway** [comment]
It look like to be related to Font Awesome. Do you still have this issue?

**Comment by tslashd** [comment]
Thank you for the response. I just tried the latest master branch (php 8.1), the icons are back and I can see current `Protests` but not archived ones. Also `Bans` and `Comms` are not showing anything now, `Submissions` still does not show anything.

**Comment by Rushaway** [comment]
Make sure you have the last commit pushed today on sbpp. https://github.com/sbpp/sourcebans-pp
ea487ef will only work with https://github.com/sbpp/sourcebans-pp/pull/883

**Comment by tslashd** [comment]
That commit exists as I downloaded the latest version of the theme from this repository and it seems that you have merged it here as well. The only one that is missing I believe is https://github.com/sbpp/sourcebans-pp/commit/fcdeb62295b2bebe113e62d5706d23c235580862

**Comment by Rushaway** [comment]
> That commit exists as I downloaded the latest version of the theme from this repository and it seems that you have merged it here as well.

Watch out on the original sbpp commit it have a function added in the include and in init.php you need them.

**Comment by tslashd** [comment]
Ahhh, my bad, apologies!
Seems that everything works now, thank you very much!
Appreciate the help! :)

P.S: I just drag and dropped the newest [SBPP release](https://github.com/sbpp/sourcebans-pp/releases/tag/1.7.0) just to make sure it's all up to date.
