### ISSUE TITLE
The ban country flags are square not rectangle (the country flags are wide)

### ISSUE THREAD

**Issue by sorelight** [Rushaway/sourcebans-web-theme-fluent#12]
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/97408934/b15f9484-e303-4878-abc0-893469a65b53)

**Comment by Rushaway** [comment]
Could you check if you have custom css for it ? (By using dev tools of your browser)
The theme doesn't have custom css for country icons, sbpp neither.

**Comment by Rushaway** [comment]
Hello it was fixed on the last release **(up to date with sbpp lastest commits)**
