### ISSUE TITLE
images/games missing in the directory of theme. Along with all images.

### ISSUE THREAD

**Issue by DEPSTRCZ** [Rushaway/sourcebans-web-theme-fluent#13]
The theme wont show a lot of icons / images beacause the folder does not exist

**Comment by Rushaway** [comment]
images/games isn't part of themes.
It's part of sbpp itself.
https://github.com/sbpp/sourcebans-pp/tree/php81/web/images/games

Regards.

**Comment by DEPSTRCZ** [comment]
> images/games isn't part of themes. It's part of sbpp itself. https://github.com/sbpp/sourcebans-pp/tree/php81/web/images/games
> 
> Regards.

Yup, sorry for that.. i was lookin into wrong dir. But i noticed it wasnt showing images/games/ls0j5e4fhws01.png which does not exist in the theme nor SBPP.. Any idea?

**Comment by DEPSTRCZ** [comment]
All solved.
