### ISSUE TITLE
Some icons do not show correctly.

### ISSUE THREAD

**Issue by DEPSTRCZ** [Rushaway/sourcebans-web-theme-fluent#14]
Not sure what could be causing this.
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/77269898/81c28956-ea95-4cc6-a274-b9375195959c)
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/77269898/9e427234-3863-404c-a303-a2aeea142fea)
Looks like a unicode / font issue

**Comment by Rushaway** [comment]
Check your browser (extensions) if it block some Javascript (from font awesome)

**Comment by DEPSTRCZ** [comment]
> Check your browser (extensions) if it block some Javascript (from font awesome) 

It is happening to multiple people across different browsers.. but I personally don't.

**Comment by Rushaway** [comment]
Wich version of Font-Awesome you're using ? Still have this issue?

**Comment by Rushaway** [comment]
Related to Font-Awesome. Please use the last commit to keep your FA version up to date.
