### ISSUE TITLE
Add space in Total Bans & Total Comms

### ISSUE THREAD

**Issue by crashzk** [Rushaway/sourcebans-web-theme-fluent#16]
Would it be possible to add a space in the message? Just a visual question, it would look like `2 (search)`.

![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/32937653/92a4dcf4-cff4-4324-a032-03dfd7ee789e)

![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/32937653/9a5185e2-21d6-4d0b-87a8-e8a3c64dfba7)

**Comment by Rushaway** [comment]
The solution of this issue is now in the linked PR.
