### ISSUE TITLE
[Request] Display map icon on server list

### ISSUE THREAD

**Issue by fbef0102** [Rushaway/sourcebans-web-theme-fluent#18]
In defaut theme
<img width="638" alt="1" src="https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/12229810/0047ed31-506e-452a-a050-5aa5fe64c1c6">

In sourcebans-web-theme-fluent theme
![2](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/12229810/c747e3eb-f8fb-45a6-b2f6-91e685f83a31)

If it disaplys map icon (the image we can upload), I will appreciate

**Comment by Rushaway** [comment]
Something like that ? (Without the gametracker banner btw)
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/11679883/7a58b4ec-df89-42ea-99e4-70f507628265)

**Comment by fbef0102** [comment]
> Something like that ? (Without the gametracker banner btw) ![image](https://user-images.githubusercontent.com/11679883/266934189-7a58b4ec-df89-42ea-99e4-70f507628265.png)

Yes.

I don't know we can use gametracker to do that. How?

**Comment by Rushaway** [comment]
Added in 1fb0790
After line 49 add this code.
You can also change banner style, by looking the doc of Gametrackers.
```
<p class="responsive_show:desktop" align="center">
	<a href="https://www.gametracker.com/server_info/{$server.ip}:{$server.port}/" target="_blank">
		<img style="border-radius: 6px;padding-left: 1px;width: 160px !important;height: auto !important;" src="https://cache.gametracker.com/server_info/{$server.ip}:{$server.port}/b_160_400_0_ffffff_c5c5c5_107abf_0f1015_0_1_0.png"/>
	</a>
</p>
```

**Comment by fbef0102** [comment]
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/12229810/08cb19eb-d74b-4cd8-bc9a-3b9bd4eafc9d)
Nice, thank you :D
