### ISSUE TITLE
[ BUG ] Color Edit Groups & Edit Admin Permissions

### ISSUE THREAD

**Issue by Rushaway** [Rushaway/sourcebans-web-theme-fluent#2]
See https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/issues/52

**Comment by Rushaway** [comment]
Fixed in https://github.com/Rushaway/sourcebans-web-theme-fluent/commit/5d08c25b9780bed94327928e9426090fa0eb70b4
Also added Menu when hover
![image](https://user-images.githubusercontent.com/11679883/175818245-eebdcc12-25c2-45d0-b8d7-c0359ef1952d.png)

**Comment by crashzk** [comment]
**@Rushaway** just an update, the bug fixed, but the option you added to add color when hovering is bugged, it's the default color, blue, even if I change the theme color.

![image](https://user-images.githubusercontent.com/32937653/187079722-51a17ed0-d60b-4f22-b208-16a7c43524ca.png)
