### ISSUE TITLE
Make the light theme the default over dark.

### ISSUE THREAD

**Issue by fleabeard69** [Rushaway/sourcebans-web-theme-fluent#24]
Any way we can default the theme to light over dark? I really dislike the sourcebans logo being partially legible in the dark theme, so I'd rather it default to light.

I know there's the sb-dark logo we can use and that's fine. Would just like to have a way to use light as the default.

**Comment by Rushaway** [comment]
Hello.
The default behavior of theme color is: 
- If the user has a system preference for dark mode and no manual override exists, the default will be dark.
- If the user has a system preference for light mode and no manual override exists, the default will be light.

If you want to apply manual change with your preference you need to edit [scripts/theme.js](https://github.com/Rushaway/sourcebans-web-theme-fluent/blob/master/sourcebans-web-theme-fluent/scripts/theme.js)

**Comment by fleabeard69** [comment]
> Hello. The default behavior of theme color is:
> 
>     * If the user has a system preference for dark mode and no manual override exists, the default will be dark.
> 
>     * If the user has a system preference for light mode and no manual override exists, the default will be light.
> 
> 
> If you want to apply manual change with your preference you need to edit [scripts/theme.js](https://github.com/Rushaway/sourcebans-web-theme-fluent/blob/master/sourcebans-web-theme-fluent/scripts/theme.js)

Thanks, what I'd like to know is what _exactly_ needs to be changed (in scripts/theme.js) to default it to white first, but allow folks to change it to dark if they prefer?

**Comment by Rushaway** [comment]
You can give a try to something like that (not tested) to adjust the logic:

```js
if (localStorage.getItem(localStorageName.color) != null) setColorTheme(localStorage.getItem(localStorageName.color));

// Check if user has manually enabled dark mode
const manualDark = localStorage.getItem(localStorageName.manualDark);

// Apply theme based on user preference or system setting
if (manualDark !== null) {
    if (manualDark == 1) {
        enableDark();
    } else {
        disableDark();
    }
} else {
    disableDark();
    if (checkDark) enableDark();
}

selectElements.colorReset.addEventListener('click', el => {

    selectElements.color.innerHTML = '';
    selectElements.colorReset.style.display = 'none';
    localStorage.removeItem(localStorageName.color);
});

selectElements.dark.addEventListener('click', el => {
    const darkModeEnabled = localStorage.getItem(localStorageName.dark) == 1;
    localStorage.setItem(localStorageName.manualDark, 1);

    if (darkModeEnabled) {
        disableDark();
    } else {
        enableDark();
    }
});
```

**Comment by fleabeard69** [comment]
> You can give a try to something like that (not tested) to adjust the logic:
> 
> ```js
> if (localStorage.getItem(localStorageName.color) != null) setColorTheme(localStorage.getItem(localStorageName.color));
> 
> // Check if user has manually enabled dark mode
> const manualDark = localStorage.getItem(localStorageName.manualDark);
> 
> // Apply theme based on user preference or system setting
> if (manualDark !== null) {
>     if (manualDark == 1) {
>         enableDark();
>     } else {
>         disableDark();
>     }
> } else {
>     disableDark();
>     if (checkDark) enableDark();
> }
> 
> selectElements.colorReset.addEventListener('click', el => {
> 
>     selectElements.color.innerHTML = '';
>     selectElements.colorReset.style.display = 'none';
>     localStorage.removeItem(localStorageName.color);
> });
> 
> selectElements.dark.addEventListener('click', el => {
>     const darkModeEnabled = localStorage.getItem(localStorageName.dark) == 1;
>     localStorage.setItem(localStorageName.manualDark, 1);
> 
>     if (darkModeEnabled) {
>         disableDark();
>     } else {
>         enableDark();
>     }
> });
> ```

This doesn't work. The default theme is still dark and when you manually change it to white and refresh the page, it just defaults back to dark heh

**Comment by Rushaway** [comment]
You also may need to edit the [Initial.js](https://github.com/Rushaway/sourcebans-web-theme-fluent/blob/master/sourcebans-web-theme-fluent/scripts/initial.js)
I will stop here, I'm not providing support for custom request, I sadly do not have enough time for that.
