### ISSUE TITLE
banslist and commslist not working

### ISSUE THREAD

**Issue by kenzopenzo1337** [Rushaway/sourcebans-web-theme-fluent#28]
https://valtora.ro/forum/hvhpanel/index.php?p=banlist
https://valtora.ro/forum/hvhpanel/index.php?p=commslist

they do not work, any fix? what did i do wrong?

**Comment by Rushaway** [comment]
What I'm suppose to see ? Its the default theme from sbpp

**Comment by kenzopenzo1337** [comment]
i reinstalled sbpp+ so i can use it till i get a fix on that, is just when i apply fluent banlist and comms list are blank, there's nothing. Tell me when to change to fluent so you can see.

**Comment by Rushaway** [comment]
You can change now, also please check if you have any errors/warning in php.

**Comment by kenzopenzo1337** [comment]
i cnahged, i do not have any warning neither errors

**Comment by Rushaway** [comment]
You can set it back to default, what version of PHP are you runnning ?
What is the theme version when you go in settings ? 
Example:
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/11679883/97086a88-ff2b-4d02-94e2-ebefd6d27c85)

**Comment by kenzopenzo1337** [comment]
Theme Author:
aXenDev
Theme Version:
1.0.6
Theme Link:
https://axendev.net/



and PHP 8.0.30

**Comment by Rushaway** [comment]
Your pages are not working because you're using an old version of the theme.
Get the last one here: https://github.com/Rushaway/sourcebans-web-theme-fluent/releases/tag/1.8.0
Also you should bump your PHP version to 8.1 or higher.
