### ISSUE TITLE
Deprecated method notice in comm blocks

### ISSUE THREAD

**Issue by maxijabase** [Rushaway/sourcebans-web-theme-fluent#6]
https://bans.electricservers.com.ar/index.php?p=commslist

**Comment by maxijabase** [comment]
Same notice here:
https://bans.electricservers.com.ar/index.php?p=commslist&searchText=STEAM_0:0:47016541&Submit

And whenever clicking on a permanent comm block, you get this where ``Unblocked by`` and ``Unblock reason`` are supposed to go:
```Warning: Undefined array key "unbanned" in /var/www/html/bans/templates_c/sourcebans_web_theme_fluent^871df9cb4ae78b97269fa86c7ec0c8fcd5b75768_0.file.page_comms.tpl.php on line 258```

**Comment by Rushaway** [comment]
> Same notice here: https://bans.electricservers.com.ar/index.php?p=commslist&searchText=STEAM_0:0:47016541&Submit
> 
> And whenever clicking on a permanent comm block, you get this where `Unblocked by` and `Unblock reason` are supposed to go: `Warning: Undefined array key "unbanned" in /var/www/html/bans/templates_c/sourcebans_web_theme_fluent^871df9cb4ae78b97269fa86c7ec0c8fcd5b75768_0.file.page_comms.tpl.php on line 258`

Related to https://github.com/sbpp/sourcebans-pp/issues/806

**Comment by Rushaway** [comment]
Fixed in https://github.com/Rushaway/sourcebans-web-theme-fluent/commit/24b0f02afe4bcf2c449999e001be55d1575f8a96 Thanks !
