### ISSUE TITLE
(website name)

### ISSUE THREAD

**Issue by HamzaJarane** [Rushaway/sourcebans-web-theme-fluent#7]
How to change this? I believe it should be pointed to >Settings/Title
![image](https://user-images.githubusercontent.com/70551889/193427478-fe3cdcaf-a153-4ebd-8053-bd76a2cf99f0.png)

**Comment by Rushaway** [comment]
@Cyclops789 Check and edit core/footer.tpl

**Comment by HamzaJarane** [comment]
Thanks!

**Comment by Rushaway** [comment]
@Cyclops789
You can also use https://github.com/Rushaway/sourcebans-pp/commit/cf60e32ad6ded4442a50469a843ae858f4b89771
And in core/footer.tpl using the new function `{$board_name}` to get you Title based on Settings/Title 👍

**Comment by Rushaway** [comment]
Closing. Was merged in PHP 8.1 Branch https://github.com/sbpp/sourcebans-pp/commit/cf60e32ad6ded4442a50469a843ae858f4b89771
