### ISSUE TITLE
more buttons in navbar

### ISSUE THREAD

**Issue by HamzaJarane** [Rushaway/sourcebans-web-theme-fluent#8]
Is it possible to add more buttons here (discord, stats)?
![image](https://user-images.githubusercontent.com/70551889/194841242-6f435c70-1e05-4eca-92a0-e163032b152c.png)

**Comment by Rushaway** [comment]
Yes. But will be hidden on mobile version for don't break the display.
You want me to give a try ?

**Comment by HamzaJarane** [comment]
Yes of course!

**Comment by Rushaway** [comment]
Do you want something like that ? Or a button like for Logout ?
**Full list of icons here :** https://fontawesome.com/search?o=r&m=free
![image](https://user-images.githubusercontent.com/11679883/194882488-e04d9bd9-d312-4372-8856-eed6e985af44.png)

**Comment by HamzaJarane** [comment]
it will be better like that 😃

**Comment by Rushaway** [comment]
I'm gonna check if i can add a settings related to it.
![image](https://user-images.githubusercontent.com/11679883/194911491-f4148fbd-f58b-494e-a1de-b4d6bfb874b7.png)
![image](https://user-images.githubusercontent.com/11679883/194911510-6a530405-9573-45e0-a04d-d77769d27a93.png)

**Comment by HamzaJarane** [comment]
Thanks 👍

**Comment by Rushaway** [comment]
Can not make a settings related to it.
SBPP doesn't support custom settings.
I will comments the code and let ppl uncomment what they want.

**Comment by HamzaJarane** [comment]
Alright, you will post it here or create a commit for it?

**Comment by Rushaway** [comment]
@Cyclops789 Commit.
Thanks for the suggestion. This feature has been added. 
If you need to edit some icons. Full list here : https://fontawesome.com/search?o=r&m=free

**Comment by HamzaJarane** [comment]
tysm!
