### ISSUE TITLE
Missing features on mobile

### ISSUE THREAD

**Issue by Wheretf2** [Rushaway/sourcebans-web-theme-fluent#9]
On mobile platforms, some admin features are missing, notably edit, comment, block comms, etc

You can see here, all options are available on desktop
![image](https://user-images.githubusercontent.com/113801019/215822763-a4ace77a-3b20-4d2f-9010-fb758bcf1327.png)

However, on mobile (or emulator), those options are unavailable
![image](https://user-images.githubusercontent.com/113801019/215822966-72cb08b1-a7b1-4cec-8c60-1bf406a9231e.png)

If its of note, they are available on larger mobile devices like an iPad (in landscape mode only), just not smaller devices like phones
![image](https://user-images.githubusercontent.com/113801019/215822852-46866f36-6876-43b5-9cca-76f1e330793b.png)

**Comment by Rushaway** [comment]
Yes. Buttons need to be re-done because it have a bad display on mobile version. It's on Todo list

**Comment by NoctisUGC** [comment]
In regards to @Wheretf2 comment. The “Search” function is no existent on mobile versions too.  Incase you are unaware.  Cannot search SteamID,s Ect

**Comment by Rushaway** [comment]
On mobile, I removed the button to connect and to get the demo.
It was not usefull in all case :
- You can connect from the slide menu
- You can not read a demo on mobile... (You can still access to it by displaying the page as browser view)

The new display on mobile
![image](https://github.com/Rushaway/sourcebans-web-theme-fluent/assets/11679883/14185fcd-dc90-4bec-8a36-107beb13e816)

**Comment by Rushaway** [comment]
[eefc849](https://github.com/Rushaway/sourcebans-web-theme-fluent/commit/eefc849f621b38e0926acf9a9c4b0b9980c045f1)
